version: '3.8'

services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    command: >
      sh -c "mkdir -p ./web/uploads/qr-codes &&
             chown -R www-data:www-data ./web/uploads &&
             apache2-foreground"     
    ports:
      - '8000:80'
    depends_on:
      - db
    networks:
      - genomed-net

  db:
    image: mysql:5.7
    container_name: genomed-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: genomed
      MYSQL_USER: genomed_user
      MYSQL_PASSWORD: "@bC12344321"
    ports:
      - '3307:3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - genomed-net

volumes:
  dbdata:

networks:
  genomed-net:
